CFLAGS = -W -Wall -Wextra -Werror 

all:Quersumme2 Quersumme oracle client

Quersumme: Quersumme.c functions.c

Quersumme2: Quersumme2.c functions.c

oracle: oracle.c 

client: client.c 

clean: 
	$(RM) Quersumme oracle client
